version: '3.1'

services:

  postgres:
    image: postgres
    volumes:
      - capstone-postgres-data:/var/lib/capstone/postgresql/data
      - ./db-scripts/postgres:/scripts
      - ./db-scripts/postgres/setup.sh:/docker-entrypoint-initdb.d/setup.sh
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
volumes:
  capstone-postgres-data: